### PR TITLE
Updated to XOMNI Public SDK v3.0.3 NuGet Package

### PR DESCRIPTION
**Pull request by nseckinoral**
-Updated SDK to v.3.0.1 NuGet Package from v3.0.0 Alpha.
-Fixed wishlistClient.GetAsync method according to SDK v3.0.1
-Fixed deviceClient.PostAsync method according to SDK v3.0.1

### CODE REVIEW

**Comment by gokhangulbiz** [comment]
Bump! @nseckinoral :)

**Comment by nseckinoral** [comment]
I already have a pbi in my backlog to review these commits. @gokhangulbiz 

Thanks for the feedback, I appreciate it. I'll remember all of your recommendations before I commit a new feature! @daronyondem

**Comment by nseckinoral** [comment]
All projects has been updated to SDK v3.0.2 and merge commits has been removed by rebasing XomniCloud/dev
I think I have a clean pull request now. What do you think?  @gokhangulbiz

**Comment by nseckinoral** [comment]
All projects has been updated to SDK v3.0.3

**Pull request closed without merging**
